import {
  PencilLine,
  ListRestart,
  Clapperboard,
  Tag,
  Calendars,
  CaseUpper,
  ListChecks,
  Percent,
  ListTodo,
  CircleQuestionMark,
  MessageSquareWarning,
  Tally3,
  ThumbsUp,
  RedoDot,
  MessageCircleQuestionMark,
  CalendarClock,
  Handshake,
  ScanFace,
  Balloon,
  Split,
  Droplet,
  List,
  ArrowUp10,
  Rose,
  Hourglass,
  SportShoe,
  Sticker,
  GlassWater,
  MessageCircleMore,
  Music4,
  BrushCleaning,
  PersonStanding,
  SunDim,
  Eraser,
  ChartNoAxesColumn,
  HandHeart,
  Footprints,
  UserStar,
  FishingRod,
  Grid2x2,
  Utensils,
  MessageCirclePlus,
  DoorOpen,
  CirclePlus,
  SquareSplitHorizontal,
  ZodiacSagittarius,
  BrickWall,
  Ban,
  Plus,
  BicepsFlexed,
  RotateCcw,
  PiggyBank,
  Timer,
  SeparatorVertical,
  ArrowDownNarrowWide,
  LayoutList,
  LayoutGrid,
  ArrowUpFromDot,
  SquareCheckBig,
  Dice5,
  Wind,
  Anchor,
  Snowflake,
  MessageSquareText,
  MessageCircleOff,
  Package2,
  Type,
  WavesArrowDown,
  UsersRound,
  Frown,
  Hand,
  ScanHeart,
  ThumbsDown,
  BedDouble,
  Sunrise,
  Clock10,
  Smartphone,
  Minimize2,
  X,
  CirclePercent,
  TextAlignJustify,
  PenOff,
  MessageCircleX,
  ArrowBigDown,
  RulerDimensionLine,
  Angry,
  MailX,
  CircleAlert,
  MessageSquareMore,
  AlarmClockPlus,
  TrendingDown,
  Pickaxe,
  AlarmClock,
  NotebookPen,
  CheckCheck,
  Tags,
  MessageSquareHeart,
  type LucideIcon,
} from "lucide-react";

export type DrillCategory =
  | "cognitive_restructuring"
  | "behavioral_activation"
  | "habit_design"
  | "grounding"
  | "self_compassion"
  | "sleep_circadian";

export interface DrillConfig {
  category: DrillCategory;
  colorVar: string;
  hex: string;
  icon: LucideIcon | null;
}

export const DRILL_CATEGORY_CONFIG: Record<
  DrillCategory,
  Pick<DrillConfig, "colorVar" | "hex">
> = {
  cognitive_restructuring: { colorVar: "--color-orange", hex: "#FFDBA9" },
  behavioral_activation: { colorVar: "--color-green", hex: "#CCF1E5" },
  habit_design: { colorVar: "--color-red", hex: "#FFB6AC" },
  grounding: { colorVar: "--color-sky", hex: "#CBEFFF" },
  self_compassion: { colorVar: "--color-pink", hex: "#FFDBE6" },
  sleep_circadian: { colorVar: "--color-indigo", hex: "#D4D5FB" },
};

interface DrillEntry {
  category: DrillCategory;
  icon: LucideIcon | null;
}

export const DRILL_CONFIG_BY_ID: Record<number, DrillEntry> = {
  1: { category: "cognitive_restructuring", icon: PencilLine },
  2: { category: "cognitive_restructuring", icon: ListRestart },
  3: { category: "cognitive_restructuring", icon: Clapperboard },
  4: { category: "cognitive_restructuring", icon: Tag },
  5: { category: "cognitive_restructuring", icon: Calendars },
  8: { category: "cognitive_restructuring", icon: CaseUpper },
  9: { category: "cognitive_restructuring", icon: ListChecks },
  11: { category: "cognitive_restructuring", icon: Percent },
  12: { category: "cognitive_restructuring", icon: ListTodo },
  13: { category: "cognitive_restructuring", icon: CircleQuestionMark },
  14: { category: "cognitive_restructuring", icon: MessageSquareWarning },
  15: { category: "cognitive_restructuring", icon: Tally3 },
  16: { category: "cognitive_restructuring", icon: ThumbsUp },
  17: { category: "cognitive_restructuring", icon: RedoDot },
  18: { category: "cognitive_restructuring", icon: MessageCircleQuestionMark },
  19: { category: "cognitive_restructuring", icon: CalendarClock },
  20: { category: "cognitive_restructuring", icon: Handshake },
  22: { category: "cognitive_restructuring", icon: ScanFace },
  24: { category: "cognitive_restructuring", icon: Balloon },
  26: { category: "cognitive_restructuring", icon: Split },
  27: { category: "cognitive_restructuring", icon: Droplet },
  70: { category: "cognitive_restructuring", icon: List },
  31: { category: "behavioral_activation", icon: ArrowUp10 },
  32: { category: "behavioral_activation", icon: Rose },
  33: { category: "behavioral_activation", icon: Hourglass },
  34: { category: "behavioral_activation", icon: SportShoe },
  35: { category: "behavioral_activation", icon: Sticker },
  37: { category: "behavioral_activation", icon: GlassWater },
  36: { category: "behavioral_activation", icon: MessageCircleMore },
  38: { category: "behavioral_activation", icon: Music4 },
  39: { category: "behavioral_activation", icon: BrushCleaning },
  40: { category: "behavioral_activation", icon: PersonStanding },
  41: { category: "behavioral_activation", icon: SunDim },
  43: { category: "behavioral_activation", icon: Eraser },
  63: { category: "behavioral_activation", icon: ChartNoAxesColumn },
  78: { category: "behavioral_activation", icon: HandHeart },
  79: { category: "behavioral_activation", icon: Footprints },
  80: { category: "behavioral_activation", icon: UserStar },
  81: { category: "behavioral_activation", icon: FishingRod },
  82: { category: "behavioral_activation", icon: Grid2x2 },
  83: { category: "behavioral_activation", icon: Utensils },
  84: { category: "behavioral_activation", icon: MessageCirclePlus },
  91: { category: "behavioral_activation", icon: DoorOpen },
  92: { category: "behavioral_activation", icon: CirclePlus },
  7: { category: "habit_design", icon: SquareSplitHorizontal },
  46: { category: "habit_design", icon: ZodiacSagittarius },
  47: { category: "habit_design", icon: BrickWall },
  49: { category: "habit_design", icon: Ban },
  52: { category: "habit_design", icon: Plus },
  53: { category: "habit_design", icon: BicepsFlexed },
  54: { category: "habit_design", icon: RotateCcw },
  55: { category: "habit_design", icon: PiggyBank },
  56: { category: "habit_design", icon: Timer },
  57: { category: "habit_design", icon: SeparatorVertical },
  76: { category: "habit_design", icon: ArrowDownNarrowWide },
  85: { category: "habit_design", icon: LayoutList },
  93: { category: "habit_design", icon: LayoutGrid },
  94: { category: "habit_design", icon: ArrowUpFromDot },
  95: { category: "habit_design", icon: SquareCheckBig },
  58: { category: "grounding", icon: Dice5 },
  59: { category: "grounding", icon: Wind },
  60: { category: "grounding", icon: Anchor },
  61: { category: "grounding", icon: Snowflake },
  62: { category: "grounding", icon: MessageSquareText },
  65: { category: "grounding", icon: MessageCircleOff },
  68: { category: "grounding", icon: Package2 },
  69: { category: "grounding", icon: Type },
  71: { category: "grounding", icon: WavesArrowDown },
  10: { category: "self_compassion", icon: UsersRound },
  72: { category: "self_compassion", icon: Frown },
  73: { category: "self_compassion", icon: Hand },
  75: { category: "self_compassion", icon: ScanHeart },
  87: { category: "self_compassion", icon: ThumbsDown },
  77: { category: "sleep_circadian", icon: BedDouble },
  88: { category: "sleep_circadian", icon: Sunrise },
  89: { category: "sleep_circadian", icon: Clock10 },
  90: { category: "sleep_circadian", icon: Smartphone },
  96: { category: "cognitive_restructuring", icon: Minimize2 },
  97: { category: "cognitive_restructuring", icon: X },
  98: { category: "cognitive_restructuring", icon: CirclePercent },
  99: { category: "cognitive_restructuring", icon: MessageSquareWarning },
  100: { category: "cognitive_restructuring", icon: TextAlignJustify },
  101: { category: "behavioral_activation", icon: MessageCircleQuestionMark },
  102: { category: "cognitive_restructuring", icon: PenOff },
  103: { category: "self_compassion", icon: MessageCircleX },
  104: { category: "cognitive_restructuring", icon: ArrowBigDown },
  105: { category: "cognitive_restructuring", icon: RulerDimensionLine },
  106: { category: "grounding", icon: Angry },
  107: { category: "self_compassion", icon: MailX },
  108: { category: "grounding", icon: CircleAlert },
  109: { category: "behavioral_activation", icon: MessageSquareMore },
  110: { category: "behavioral_activation", icon: AlarmClockPlus },
  111: { category: "habit_design", icon: TrendingDown },
  112: { category: "habit_design", icon: Pickaxe },
  113: { category: "sleep_circadian", icon: AlarmClock },
  114: { category: "sleep_circadian", icon: NotebookPen },
  115: { category: "grounding", icon: Dice5 },
  116: { category: "behavioral_activation", icon: CheckCheck },
  117: { category: "grounding", icon: Tags },
  118: { category: "self_compassion", icon: MessageSquareHeart },
};

export function getDrillConfig(drillId: number): DrillConfig | null {
  const entry = DRILL_CONFIG_BY_ID[drillId];
  if (!entry) return null;
  return {
    category: entry.category,
    icon: entry.icon,
    ...DRILL_CATEGORY_CONFIG[entry.category],
  };
}
